import { StyleSheet } from 'react-native';
import { Fonts } from 'font_directory/Fonts';
import { width0_5, width1, width10, width2, width5 } from '../_global/able-soft-component-ui/src/assets/dimensions/width';
import { normalize, normalize2 } from '../../../Gloabal/GlobalFunctions';
import { width12, width13, width13_5, width14, width14_5, width15, width16 } from '../../utils/dimensions/width';

export default StyleSheet.create({
    rootContainer: {
        flexDirection: 'row',
        width: '100%',
        alignSelf: 'center',
        height:width14_5,
        justifyContent: 'center',
        backgroundColor: '#f6f7f8',
        justifyContent: 'space-evenly',
        shadowRadius: 2,
        borderTopWidth: 1.5,
        borderColor: '#e1e2e3',
        paddingHorizontal: '5%',
        borderWidth: 1,
        // marginTop:5
    },
    tabContainer: {
        justifyContent: 'center',
        flex: 1,
        height: width14_5,
        alignSelf: 'center',
    },
    showSendButton: {
        width: 60,
        height: 60,
        right: 0,
        position: 'absolute',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 10,
        justifyContent: 'center',
        elevation: 30,
    },
    sendContainer: {
        flexDirection: 'row',
        width: '80%',
        height: 50,
        alignSelf: 'center',
        backgroundColor: 'white',
        justifyContent: 'space-between',
        borderRadius: 35,
        borderWidth: 2,
        bottom: 10,
        borderColor: 'gray',
        paddingHorizontal: 15,
    },
    sendButton: {
        width: 50,
        height: 50,
        borderRadius: 35,
        alignSelf: 'center',
        backgroundColor: 'rgba(68, 221, 255,0.7)',
        justifyContent: 'center',
    },
    hideSendButton: {
        width: 60,
        height: 70,
        left: 0,
        position: 'absolute',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderTopRightRadius: 35,
        borderBottomRightRadius: 35,
        justifyContent: 'center',
        elevation: 30,
        // transform: [{rotate: '180deg'}],
    },
    inputStyle: {
        flex: 1,
        height: 50,
        marginHorizontal: 10,
        borderBottomWidth: 2,
        paddingHorizontal: 5,
        borderColor: 'gray',
        alignSelf: 'center',
    },
    countContainer: {
        position: 'absolute',
        top: -9,
        borderRadius: 10,
        paddingHorizontal: 6,
        height: width5,
        backgroundColor: '#ff3f4c',
        alignSelf: 'center',
        justifyContent: 'center',
    },
    radiusBorderTop: {
        position: 'absolute',
        borderRadius: 2,
        width: 4,
        height: 4,
        width: '100%',
        backgroundColor: 'green',
        alignSelf: 'center',
        justifyContent: 'center',
        top: -1.8,
    },
    countText: {
        color: 'white',
        fontSize: normalize2(11),
        fontFamily: Fonts.ArialBold,
        alignSelf: 'center',
        textAlign: 'center',
    },
});
