
import { width90, width85, width70, width50 } from '../../../utils/dimensions/width';
const React = require('react-native');
import { Fonts } from 'font_directory/Fonts';
const { StyleSheet } = React;
const buttonGroup = () => {
    return {
        flexDirection: 'row',
        width: width85 / 2 - 10,
        justifyContent: 'space-evenly',
        alignSelf: 'center',
        backgroundColor: '#e8ecf0',
        height: 35,
        borderRadius: 8,
    };
};
const buttonGroupText = () => {
    return {
        fontSize: 15,
        fontFamily: Fonts.Arial,
        color: '#717f8e',
        alignSelf: 'center',
    };
};
module.exports = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: 'white',
    },
    userIconContainer: {
        alignSelf: 'center',
        width: 80,
        height: 80,
        marginTop: 20,
    },
    userIcon: {
        alignSelf: 'center',
        width: 80,
        height: 80,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: '#EEEEEE',
        backgroundColor: 'gray',
    },
    roomName: {
        fontSize: 18,
        fontFamily: Fonts.ArialBold,
        color: '#3b4252',
        alignSelf: 'center',
        marginTop: 10,
        textAlign: 'center',
    },
    activeDate: {
        fontSize: 13,
        fontFamily: Fonts.Arial,
        color: '#3b4252',
        alignSelf: 'center',
        marginBottom: 10,
    },
    FixButton: {
        backgroundColor: 'rgb(230,238,245)',
        alignSelf: 'center',
        marginTop: 5,
        marginBottom: 15,
        padding: 5,
        paddingHorizontal: 10,
        borderRadius: 15,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: 'rgb(223,230,238)',
    },
    UserListButton: {
        backgroundColor: '#f3f8fa',
        alignSelf: 'center',
        padding: 5,
        paddingHorizontal: 10,
        borderRadius: 10,
        flexDirection: 'row',
        width: width85,
        borderWidth: 1,
        borderColor: '#c7d3db',
        height: 40,
        justifyContent: 'center',
        marginBottom: 10,
    },
    buttonGroupContainer: {
        flexDirection: 'row',
        width: width85,
        justifyContent: 'space-between',
        alignSelf: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    buttonGroup: Object.assign(buttonGroup(), { backgroundColor: 'rgb(231,237,242)' }),
    buttonGroupSelected: Object.assign(buttonGroup(), { backgroundColor: 'rgb(74,116,177)' }),
    buttonGroupText: Object.assign(buttonGroupText(), { color: '#717f8e' }),
    buttonGroupTextSelected: Object.assign(buttonGroupText(), { color: 'white' }),
    UserListButtonText: {
        fontSize: 15,
        fontFamily: Fonts.Arial,
        color: '#8aa1b1',
        alignSelf: 'center',
        marginLeft: 10,
    },
    FixButtonText: {
        fontSize: 12,
        fontFamily: Fonts.Arial,
        color: '#3b4252',
        alignSelf: 'center',
    },
    usersEndIcon: {
        alignSelf: 'center',
        position: 'absolute',
        right: 20,
    },
    settingColumnContainer: {
        flexDirection: 'row',
        width: '100%',
        height: 40,
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    groupIcon: {
        alignSelf: 'flex-start',
        width: 50,
        height: 50,
        borderRadius: 20,
        borderWidth: 0.5,
        borderColor: 'white',
        marginRight: 10,
    },
    settingName: {
        fontSize: 16,
        fontFamily: Fonts.Arial,
        color: 'black',
        marginTop: 10,
    },
    modalHeader: {
        fontSize: 16,
        fontFamily: Fonts.Arial,
        color: 'black',
    },
    modalBody: {
        fontSize: 14,
        fontFamily: Fonts.Arial,
        color: '#3b4252',
        marginVertical: 15,
        textAlign: 'center',
    },
    modalButtonText: {
        fontSize: 14,
        fontFamily: Fonts.ArialBold,
        color: 'white',
        alignSelf: 'center',
    },
    modalButton: {
        marginTop: 10,
        width: width50 / 2,
        borderRadius: 5,
        backgroundColor: '#4a72b1',
        justifyContent: 'center',
        height: 40,
        alignSelf: 'flex-end',
    },
    activeCircle: {
        width: 25,
        height: 25,
        borderRadius: 12.5,
        backgroundColor: '#5aed70',
        position: 'absolute',
        right: 0,
        bottom: 0,
        borderWidth: 2,
        borderColor: 'white',
    },
    searchInput: {
        width: width90,
        backgroundColor: '#EEEEEE',
        borderRadius: 10,
        height: 35,
        paddingHorizontal: 20,
        alignSelf: 'center',
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    searchInputText: {
        fontSize: 15,
        fontFamily: Fonts.Arial,
        color: 'gray',
        alignSelf: 'center',
    },
    roomNameChangeContainer: {
        width: width90,
        backgroundColor: 'white',
        justifyContent: 'flex-start',
        alignSelf: 'center',
        borderRadius: 8,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.25,
        elevation: 5,
    },
    textInputContainer: {
        borderWidth: 1,
        borderColor: '#c3c7db',
        backgroundColor: '#f3f8fa',
        width: '100%',
        maxHeight: 80,
        padding: 5,
        marginBottom: 40,
        flexDirection: 'row',
        borderRadius: 5,
    },
    textInput: {
        width: '90%',
        maxHeight: 50,
        height: null,
        fontFamily: Fonts.ArialBold,
        fontSize: 16,
        alignSelf: 'center',
        padding: 0,
    },
    roomPictureChangeContainer: {
        width: width70,
        backgroundColor: 'white',
        justifyContent: 'flex-start',
        alignSelf: 'center',
        borderRadius: 5,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.25,
        elevation: 5,
    },
    listContainerStyle: {
        marginTop: 10,
        paddingBottom: 50,
        paddingStart: 3,
    },
    listStyle: {
        flex: 1,
        width: width85 + 6,
        alignSelf: 'center',
    },
    roomFixIcon: {
        alignSelf: 'center',
        marginRight: 10,
        position: 'absolute',
        right: 0,
        top: 10,
    },
    modalStyle: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    imageContainer: {
        height: 120,
        width: 120,
        alignSelf: 'center',
        marginVertical: 30,
        justifyContent: 'center',
    },
    imageStyle: {
        height: 120,
        width: 120,
        borderRadius: 50,
        alignSelf: 'center',
    },
    imageAbsolute: {
        position: 'absolute',
        height: 120,
        width: 120,
        borderRadius: 50,
        backgroundColor: 'rgba(0,0,0,0.1)',
        justifyContent: 'center',
    },
    modalSaveButton: {
        width: '100%',
        alignSelf: 'flex-end',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 10,
    },
    camerIcon: {
        position: 'absolute',
        alignSelf: 'center',
        left: 35,
    },
});
