import { Dimensions, Platform } from 'react-native';
const width85 = (Dimensions.get('window').width * 85) / 100;
const React = require('react-native');
import { Fonts } from 'font_directory/Fonts';
import {
    width90,
    width20,
    width50,
    width10,
    width5,
    width4,
    width14,
    width15,
    width12,
    width3_5,
    width18,
    width16,
    width70,
} from '../../utils/dimensions/width';
import { normalize, normalize2 } from '../../../Gloabal/GlobalFunctions';
import {
    width1,
    width100,
    width2,
    width3,
    width30,
    width40,
    width8,
    width9,
} from '../../_Components/_global/able-soft-component-ui/src/assets/dimensions/width';
let { StyleSheet } = React;

module.exports = StyleSheet.create({
    userIconContainer: {
        alignSelf: 'center',
        width: 80,
        height: 80,
        marginTop: 20,
    },
    userIcon: {
        alignSelf: 'center',
        width: 80,
        height: 80,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: '#EEEEEE',
        backgroundColor: 'gray',
    },
    userName: {
        fontSize: normalize2(18),
        fontFamily: Fonts.ArialBold,
        color: '#3b4252',
        alignSelf: 'center',
        marginTop: 10,
        textAlign: 'center',
    },
    position: {
        fontSize: normalize2(15),
        fontFamily: Fonts.Arial,
        color: 'gray',
        alignSelf: 'center',
        // marginTop: 5,
        textAlign: 'center',
    },
    activeDate: {
        fontSize: 13,
        fontFamily: Fonts.Arial,
        color: '#3b4252',
        alignSelf: 'center',
        marginBottom: 5,
    },
    FixButton: {
        backgroundColor: 'rgb(230,238,245)',
        alignSelf: 'center',
        marginTop: 5,
        marginBottom: 15,
        padding: 5,
        paddingHorizontal: 10,
        borderRadius: 15,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: 'rgb(223,230,238)',
    },
    LogoutButton: {
        backgroundColor: 'rgb(249,200,199)',
        alignSelf: 'center',
        padding: 5,
        paddingHorizontal: 10,
        borderRadius: 10,
        flexDirection: 'row',
        width: width85,
        height: 40,
        justifyContent: 'center',
        position: 'absolute',
        bottom: 30,
        borderWidth: 1,
    },
    LogoutButtonText: {
        textAlign: 'center',
        color: 'rgb(205,102,99)',
        fontFamily: Fonts.ArialBold,
        alignSelf: 'center',
        fontSize: 18,
    },
    userDataContainer: {
        paddingTop: width8,
        marginHorizontal: 10,
        alignItems: 'center',
    },
    containerStyle: {
        backgroundColor: 'white',
        paddingBottom: width5,
    },
    introContainer: {
        width: width90,
        backgroundColor: '#f46062',
        borderRadius: 10,
        marginTop: width5,
        paddingHorizontal: width4,
        paddingVertical: width2,
    },
    introText: {
        fontSize: normalize2(16),
        color: 'white',
        marginBottom: 3,
    },
    menuContainer: {
        padding: 5,
        alignSelf: 'center',
        marginVertical: width10,
    },
    sheetBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: -1000,
        right: 0,
        backgroundColor: 'rgba(16,48,84,0.85)',
        // backgroundColor:'red',
        zIndex: 1,
    },
    sheetContainer: {
        width: width100,
        backgroundColor: 'white',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        paddingHorizontal: width10,
        paddingVertical: width5,
        flex: 1,
    },
    titleText: {
        textAlign: 'center',
        fontSize: normalize2(16),
        fontWeight: 'bold',
        color: 'black',
        marginHorizontal: width15,
    },
    chatContainer: {
        height: width40,
        borderBottomWidth: 2,
        backgroundColor: 'white',
        marginTop: width10,
        borderColor: '#DBDCE0',
    },
    rowChatSection: {},
    graySection: {
        width: width50,
        height: width12,
        backgroundColor: '#EBECEE',
        borderRadius: 10,
    },
    mySection: {
        width: width50,
        height: width20,
        backgroundColor: '#347FE5',
        borderRadius: 10,
        marginTop: width3_5,
        marginLeft: width30,
        elevation: 3,
    },
    colorCircleContainer: {
        width: width14,
        height: width16,
        marginHorizontal: width3,
        alignItems: 'center',
        paddingTop: width1,
    },
    colorContainer: {
        flex: 1,
        borderRadius: 15,
    },
    selectButtonContainer: {
        width: width50,
        height: width12,
        backgroundColor: '#1f76e4',
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        marginBottom:Platform.OS==='ios'?width4: width2,
    },
    downSelectButtonContainer: {
        width: width50,
        height: width12,
        backgroundColor: '#96bbea',
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        marginBottom:Platform.OS==='ios'?width4: width2,
    },
    selectText: {
        color: 'white',
        fontSize: normalize2(16),
        fontWeight: 'bold',
        marginBottom: 2,
    },
    downSelectText: {
        color: '#4677b6',
        fontSize: normalize2(16),
        fontWeight: 'bold',
        marginBottom: 2,
    },
    checkIconStyle: {
        marginRight: width2,
        marginBottom: 2,
    },
    colorListStyle: {
        borderWidth: 1,
        height: width10,
    },

    logOutModalContainer: {
        width:width70,
    backgroundColor:'white',
    alignSelf:'center',
    borderRadius:10,
    padding:width5
    },
    modalText: {
    textAlign:'center',
    fontSize:normalize2(15),
    color:'black',
    marginTop:width5
    },
    yesButtonContainer:{
        width:width20,
        height:width10,
        backgroundColor:'#2277e5',
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center',
        marginTop:width5,
        borderRadius:10,
        marginBottom:width5
    },
    DownyesButtonContainer:{
        width:width20,
        height:width10,
        backgroundColor:'#96bbea',
        alignItems:'center',
        justifyContent:'center',
        alignSelf:'center',
        marginTop:width5,
        borderRadius:10,
        marginBottom:width5
    },
    yesText:{
        marginBottom:2,
        color:'white',
        fontSize:normalize2(13),
        fontWeight:'bold'
    },
    DownyesText:{
        marginBottom:2,
        color:'#4677b6',
        fontSize:normalize2(13),
        fontWeight:'bold'
    }
});
